# Data Cleaning and Preparation

In [3]:
import pandas as pd
import ast

In [ ]:
df = pd.read_csv(r"C:\Users\path\to\steam_games.csv")
df

C:\Users\Tina White Gaming\AppData\Local\Temp\ipykernel_23748\3437872560.py:1: DtypeWarning: Columns (0: windows, 1: mac, 2: linux) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\Tina White Gaming\Desktop\My Portfolio\Projects from scratch\Python Pandas\Steam_Games\steam_games.csv")

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,linux,header_image,screenshots,movies,website,support_url,support_email,metacritic_url,steam_store_available,steam_spy_available
0,922630,Mortal Royale,2018-12-17,0.00,free,50000 - 100000,"[""Star Vault AB""]","[""Star Vault AB""]","[""Action"", ""Free To Play"", ""Early Access""]","[""Multi-player"", ""PvP"", ""Online PvP""]",...,False,https://shared.akamai.steamstatic.com/store_it...,"[""https://shared.akamai.steamstatic.com/store_...",[],https://www.mortalroyale.com/,https://mortalroyale.com/forums/,mortalroyale@starvault.se,NaN,True,True
1,922650,Caveman Chuck,2018-09-20,4.99,paid,0 - 20000,"[""Prime Bit Games SA""]","[""Prime Bit Games SA""]","[""Action"", ""Adventure""]","[""Single-player"", ""Partial Controller Support""...",...,False,https://shared.akamai.steamstatic.com/store_it...,"[""https://shared.akamai.steamstatic.com/store_...",[],https://primebitgames.com/games/#Caveman_Chuck,http://primebitgames.com,support@primebitgames.com,NaN,True,True
2,922700,Hidden Animals: Photo Hunt - Worldwide Safari,2018-10-18,2.99,paid,0 - 20000,"[""Crisp App Studio""]","[""Crisp App Studio""]","[""Adventure"", ""Casual"", ""Indie""]","[""Single-player"", ""Steam Achievements"", ""Steam...",...,False,https://shared.akamai.steamstatic.com/store_it...,"[""https://shared.akamai.steamstatic.com/store_...",[],NaN,http://facebook/CrispApp,support@crispapp.com,NaN,True,True
3,922710,Knightin'+,2019-07-26,5.99,paid,20000 - 50000,"[""Muzt Die Studios""]","[""Muzt Die Studios""]","[""Action"", ""Adventure"", ""Indie""]","[""Single-player"", ""Steam Achievements"", ""Full ...",...,True,https://shared.akamai.steamstatic.com/store_it...,"[""https://shared.akamai.steamstatic.com/store_...",[],NaN,NaN,muztdiestudios@gmail.com,NaN,True,True
4,922810,MeatPossible: Chapter 1.5,2018-09-19,3.99,paid,0 - 20000,"[""Common Visual Entertainment""]","[""Common Visual Entertainment""]","[""Action"", ""Adventure"", ""Indie""]","[""Single-player"", ""Steam Achievements"", ""Full ...",...,True,https://shared.akamai.steamstatic.com/store_it...,"[""https://shared.akamai.steamstatic.com/store_...",[],https://meatpossible.com/,https://meatpossible.com/,qrt@meatpossible.com,NaN,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140736,4240,RACE - The WTCC Game,2006-11-24,39.99,paid,"200,000 .. 500,000","[""SimBin""]","[""SimBin""]","[{""id"": ""9"", ""description"": ""Racing""}]","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,False,https://shared.akamai.steamstatic.com/store_it...,"[{""id"": 0, ""path_thumbnail"": ""https://shared.a...",[],http://www.race-game.org/,NaN,work@simbin.com,NaN,True,True
140737,4500,S.T.A.L.K.E.R.: Shadow of Chernobyl,2007-03-20,19.99,paid,"1,000,000 .. 2,000,000","[""GSC Game World""]","[""GSC Game World""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,False,https://shared.akamai.steamstatic.com/store_it...,"[{""id"": 0, ""path_thumbnail"": ""https://shared.a...",[],https://soc.stalker-game.com/,https://soc.stalker-game.com/?page=support,support@gsc-game.com,https://www.metacritic.com/game/pc/stalker-sha...,True,True
140738,4780,Medieval II: Total War™ Kingdoms,2007-08-28,24.99,paid,"200,000 .. 500,000","[""CREATIVE ASSEMBLY"", ""Feral Interactive (Mac)...","[""SEGA"", ""Feral Interactive (Mac)"", ""Feral Int...","[{""id"": ""2"", ""description"": ""Strategy""}]","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,True,https://shared.akamai.steamstatic.com/store_it...,"[{""id"": 0, ""path_thumbnail"": ""https://shared.a...","[{""id"": 900520, ""name"": ""Medieval II: Total Wa...",http://www.totalwar.com,https://support.sega.co.uk,NaN,https://www.metacritic.com/game/pc/medieval-ii...,True,True
140739,4932,Natural Selection 2,2012-10-30,4.99,paid,"0 .. 20,000","[""Unknown Worlds Entertainment""]","[""Unknown Worlds Entertainment"", ""KRAFTON, Inc.""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 1, ""description"": ""Multi-player""}, {""i...",...,False,https://shared.akamai.steamstatic.com/store_it...,"[{""id"": 0, ""path_thumbnail"": ""https://shared.a...","[{""id"": 2029265, ""name"": ""Natural Selection 2 ...",http://www.naturalselection2.com,https://support.krafton.com,NaN,https://www.metacritic.com/game/pc/natural-sel...,True,True
140740,6129,Shank,2010-10-25,9.99,paid,"0 .. 20,000","[""Klei Entertainment""]","[""Klei Entertainment""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,True,https://shared.akamai.steamstatic.com/store_it...,"[{""id"": 0, ""path_thumbnail"": ""https://shared.a...","[{""id"": 5951, ""name"": ""Shank Trailer"", ""thumbn...",http://www.shankgame.com,http://support.kleientertainment.com,support@kleientertainment.com,https://www.metacritic.com/game/pc/shank?ftag=...,True,True

### Examine the data

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 140741 entries, 0 to 140740
Data columns (total 42 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   app_id                    140741 non-null  int64
 1   name                      140724 non-null  str
 2   release_date              140658 non-null  str
 3   price                     139526 non-null  float64
 4   price_status              140741 non-null  str
 5   estimated_owners          140741 non-null  str
 6   developers                140741 non-null  str
 7   publishers                140741 non-null  str
 8   genres                    140741 non-null  str
 9   categories                140741 non-null  str
 10  tags                      140741 non-null  str
 11  positive                  140741 non-null  int64
 12  negative                  140741 non-null  int64
 13  recommendations           106731 non-null  float64
 14  peak_ccu                  140741 non-null  int64
 15  metacritic_score          99515 non-null   float64
 16  user_score                140741 non-null  int64
 17  average_playtime_forever  140741 non-null  int64
 18  median_playtime_forever   140741 non-null  int64
 19  average_playtime_2weeks   140741 non-null  int64
 20  median_playtime_2weeks    140741 non-null  int64
 21  short_description         132410 non-null  str
 22  about_the_game            132304 non-null  str
 23  detailed_description      132325 non-null  str
 24  notes                     26293 non-null   str
 25  achievements              122802 non-null  float64
 26  dlc_count                 140741 non-null  int64
 27  packages                  140741 non-null  str
 28  supported_languages       140721 non-null  str
 29  full_audio_languages      107234 non-null  str
 30  windows                   140726 non-null  object
 31  mac                       140726 non-null  object
 32  linux                     140726 non-null  object
 33  header_image              140643 non-null  str
 34  screenshots               140741 non-null  str
 35  movies                    140741 non-null  str
 36  website                   54662 non-null   str
 37  support_url               60629 non-null   str
 38  support_email             116487 non-null  str
 39  metacritic_url            4290 non-null    str
 40  steam_store_available     140741 non-null  bool
 41  steam_spy_available       140741 non-null  bool
dtypes: bool(2), float64(4), int64(10), object(3), str(23)
memory usage: 914.6+ MB

In [6]:
df.isnull().sum()

app_id                           0
name                            17
release_date                    83
price                         1215
price_status                     0
estimated_owners                 0
developers                       0
publishers                       0
genres                           0
categories                       0
tags                             0
positive                         0
negative                         0
recommendations              34010
peak_ccu                         0
metacritic_score             41226
user_score                       0
average_playtime_forever         0
median_playtime_forever          0
average_playtime_2weeks          0
median_playtime_2weeks           0
short_description             8331
about_the_game                8437
detailed_description          8416
notes                       114448
achievements                 17939
dlc_count                        0
packages                         0
supported_languages             20
full_audio_languages         33507
windows                         15
mac                             15
linux                           15
header_image                    98
screenshots                      0
movies                           0
website                      86079
support_url                  80112
support_email                24254
metacritic_url              136451
steam_store_available            0
steam_spy_available              0
dtype: int64

### Delete useless columns

In [7]:
df2 = df.drop(columns = ["short_description", "about_the_game", "detailed_description", "notes", "supported_languages", "full_audio_languages", "header_image", "screenshots", "movies", "website", "support_url", "support_email", "metacritic_url", "steam_store_available", "steam_spy_available", "packages"])
# df2

### Explore the new dataframe

In [8]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 140741 entries, 0 to 140740
Data columns (total 26 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   app_id                    140741 non-null  int64
 1   name                      140724 non-null  str
 2   release_date              140658 non-null  str
 3   price                     139526 non-null  float64
 4   price_status              140741 non-null  str
 5   estimated_owners          140741 non-null  str
 6   developers                140741 non-null  str
 7   publishers                140741 non-null  str
 8   genres                    140741 non-null  str
 9   categories                140741 non-null  str
 10  tags                      140741 non-null  str
 11  positive                  140741 non-null  int64
 12  negative                  140741 non-null  int64
 13  recommendations           106731 non-null  float64
 14  peak_ccu                  140741 non-null  int64
 15  metacritic_score          99515 non-null   float64
 16  user_score                140741 non-null  int64
 17  average_playtime_forever  140741 non-null  int64
 18  median_playtime_forever   140741 non-null  int64
 19  average_playtime_2weeks   140741 non-null  int64
 20  median_playtime_2weeks    140741 non-null  int64
 21  achievements              122802 non-null  float64
 22  dlc_count                 140741 non-null  int64
 23  windows                   140726 non-null  object
 24  mac                       140726 non-null  object
 25  linux                     140726 non-null  object
dtypes: float64(4), int64(10), object(3), str(9)
memory usage: 77.8+ MB

In [9]:
df2.describe()

,app_id,price,positive,negative,recommendations,peak_ccu,metacritic_score,user_score,average_playtime_forever,median_playtime_forever,average_playtime_2weeks,median_playtime_2weeks,achievements,dlc_count
count,1.407410e+05,139526.000000,1.407410e+05,1.407410e+05,1.067310e+05,1.407410e+05,99515.000000,140741.000000,140741.000000,140741.000000,140741.000000,140741.000000,122802.000000,140741.000000
mean,2.262936e+06,9.010596,9.106742e+02,1.475454e+02,1.157531e+03,4.762170e+01,3.189931,0.021387,78.251050,69.929097,6.295976,6.694190,20.594648,0.502306
std,1.274100e+06,409.461707,2.622234e+04,5.016871e+03,2.456990e+04,3.481079e+03,15.179119,1.301985,1990.166986,1971.150398,154.893180,169.289593,150.266575,13.501431
min,1.000000e+01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.177940e+06,0.990000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2.172980e+06,4.990000,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,0.000000
75%,3.271090e+06,9.990000,2.600000e+01,7.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21.000000,0.000000
max,5.180470e+06,107500.000000,7.642084e+06,1.173003e+06,5.179195e+06,1.013936e+06,97.000000,100.000000,359665.000000,359674.000000,20014.000000,20014.000000,10979.000000,3703.000000

In [10]:
df2.nunique()

app_id                      140741
name                        139307
release_date                  5328
price                          984
price_status                     3
estimated_owners                27
developers                   83101
publishers                   74419
genres                        4127
categories                   21073
tags                         80290
positive                      5542
negative                      2728
recommendations               5424
peak_ccu                      1111
metacritic_score                73
user_score                      31
average_playtime_forever      2249
median_playtime_forever       2042
average_playtime_2weeks        757
median_playtime_2weeks         766
achievements                   439
dlc_count                      118
windows                          2
mac                              2
linux                            2
dtype: int64

### Examine the genre column

In [11]:
df2['genres'].explode().value_counts()

genres
[]                                                                                                                 8432
["Casual", "Indie"]                                                                                                6234
["Action", "Adventure", "Indie"]                                                                                   4245
["Action", "Indie"]                                                                                                4173
["Adventure", "Indie"]                                                                                             3549
                                                                                                                   ...
["Simulation", "Education", "Video Production", "Early Access"]                                                       1
["Casual", "Free To Play", "Animation & Modeling", "Design & Illustration", "Utilities"]                              1
["Simulation", "Free To Play", "Education"]                                                                           1
["Strategy", "Utilities"]                                                                                             1
["Action", "Adventure", "Casual", "Massively Multiplayer", "RPG", "Simulation", "Free To Play", "Early Access"]       1
Name: count, Length: 4127, dtype: int64

In [12]:
df2[df2['genres'].str.contains('Action')]

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,user_score,average_playtime_forever,median_playtime_forever,average_playtime_2weeks,median_playtime_2weeks,achievements,dlc_count,windows,mac,linux
0,922630,Mortal Royale,2018-12-17,0.00,free,50000 - 100000,"[""Star Vault AB""]","[""Star Vault AB""]","[""Action"", ""Free To Play"", ""Early Access""]","[""Multi-player"", ""PvP"", ""Online PvP""]",...,0,15,21,0,0,0.0,1,True,False,False
1,922650,Caveman Chuck,2018-09-20,4.99,paid,0 - 20000,"[""Prime Bit Games SA""]","[""Prime Bit Games SA""]","[""Action"", ""Adventure""]","[""Single-player"", ""Partial Controller Support""...",...,0,0,0,0,0,0.0,0,True,False,False
3,922710,Knightin'+,2019-07-26,5.99,paid,20000 - 50000,"[""Muzt Die Studios""]","[""Muzt Die Studios""]","[""Action"", ""Adventure"", ""Indie""]","[""Single-player"", ""Steam Achievements"", ""Full ...",...,0,100,165,0,0,22.0,1,True,True,True
4,922810,MeatPossible: Chapter 1.5,2018-09-19,3.99,paid,0 - 20000,"[""Common Visual Entertainment""]","[""Common Visual Entertainment""]","[""Action"", ""Adventure"", ""Indie""]","[""Single-player"", ""Steam Achievements"", ""Full ...",...,0,0,0,0,0,18.0,0,True,True,True
9,923030,Rocket Swords,2018-09-10,0.00,free,0 - 20000,"[""Michael Crabbs""]","[""Michael Crabbs""]","[""Action""]","[""Single-player"", ""Tracked Controller Support""...",...,0,0,0,0,0,0.0,0,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140731,659,Portal 2,2011-04-18,9.99,paid,"0 .. 20,000","[""Valve""]","[""Valve""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,0,0,51.0,1,True,False,True
140733,2130,Dark Messiah of Might & Magic,2006-10-25,9.99,paid,"1,000,000 .. 2,000,000","[""Arkane Studios""]","[""Ubisoft""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,0,0,NaN,0,True,False,False
140737,4500,S.T.A.L.K.E.R.: Shadow of Chernobyl,2007-03-20,19.99,paid,"1,000,000 .. 2,000,000","[""GSC Game World""]","[""GSC Game World""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,0,0,NaN,0,True,False,False
140739,4932,Natural Selection 2,2012-10-30,4.99,paid,"0 .. 20,000","[""Unknown Worlds Entertainment""]","[""Unknown Worlds Entertainment"", ""KRAFTON, Inc.""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 1, ""description"": ""Multi-player""}, {""i...",...,0,0,0,0,0,137.0,10,True,False,False
140740,6129,Shank,2010-10-25,9.99,paid,"0 .. 20,000","[""Klei Entertainment""]","[""Klei Entertainment""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,0,0,12.0,0,True,True,True

In [13]:
df2[df2['genres'].str.contains('description')]

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,user_score,average_playtime_forever,median_playtime_forever,average_playtime_2weeks,median_playtime_2weeks,achievements,dlc_count,windows,mac,linux
85704,2733000,Club Chairman,2026-08-14,2.99,unavailable,"0 .. 20,000","[""Ashina Games""]","[""Ashina Games""]","[{""id"": ""4"", ""description"": ""Casual""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,0,0,NaN,0,True,True,True
85705,3130050,Stellar Odyssey,2026-08-14,14.99,unavailable,"0 .. 20,000","[""Warp Studios Pty Ltd""]","[""Warp Studios Pty Ltd""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,0,0,29.0,0,True,False,False
85706,2566840,Sands of Skullcreek,2026-08-14,0.00,unavailable,"0 .. 20,000","[""Fallen Sun Arcade""]","[""Fallen Sun Arcade""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,0,0,NaN,0,True,False,False
85707,2507500,Bounty Hunters,2026-08-15,5.00,unavailable,"0 .. 20,000","[""AntiCodec""]","[""AntiCodec""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,0,0,15.0,0,True,False,False
85708,2825810,PhotoGuessr,2026-08-15,3.99,unavailable,"0 .. 20,000","[""Studio Pakira""]","[""Studio Pakira""]","[{""id"": ""4"", ""description"": ""Casual""}]","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,0,0,10.0,0,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140736,4240,RACE - The WTCC Game,2006-11-24,39.99,paid,"200,000 .. 500,000","[""SimBin""]","[""SimBin""]","[{""id"": ""9"", ""description"": ""Racing""}]","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,0,0,NaN,0,True,False,False
140737,4500,S.T.A.L.K.E.R.: Shadow of Chernobyl,2007-03-20,19.99,paid,"1,000,000 .. 2,000,000","[""GSC Game World""]","[""GSC Game World""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,0,0,NaN,0,True,False,False
140738,4780,Medieval II: Total War™ Kingdoms,2007-08-28,24.99,paid,"200,000 .. 500,000","[""CREATIVE ASSEMBLY"", ""Feral Interactive (Mac)...","[""SEGA"", ""Feral Interactive (Mac)"", ""Feral Int...","[{""id"": ""2"", ""description"": ""Strategy""}]","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,0,0,NaN,0,True,True,True
140739,4932,Natural Selection 2,2012-10-30,4.99,paid,"0 .. 20,000","[""Unknown Worlds Entertainment""]","[""Unknown Worlds Entertainment"", ""KRAFTON, Inc.""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 1, ""description"": ""Multi-player""}, {""i...",...,0,0,0,0,0,137.0,10,True,False,False
140740,6129,Shank,2010-10-25,9.99,paid,"0 .. 20,000","[""Klei Entertainment""]","[""Klei Entertainment""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,0,0,12.0,0,True,True,True

### As we can see, the genres, categories and tags columns have the same information stored in different formats. We want to change the values that is a list of dictionaries.

### Function to turn the text inside the column to a consistent Python list:

In [14]:
def clean (value):
    if pd.isna(value):
        return []

    try:
        parsed = ast.literal_eval(value)

        # Format: ["Action", "Adventure"]
        if isinstance(parsed, list) and all(isinstance(x, str) for x in parsed):
            return parsed

        # Format: [{"id": "1", "description": "Action"}, ...]
        if isinstance(parsed, list) and all(isinstance(x, dict) for x in parsed):
            return [x.get("description") for x in parsed if x.get("description")]

    except:
        return []

    return []

### Clean the genre column

In [15]:
df2['genres_clean'] = df2['genres'].apply(clean)

df2['genres_clean'].explode().value_counts()

genres_clean
Indie                    93690
Casual                   59020
Action                   52419
Adventure                51053
Simulation               28782
Strategy                 26687
RPG                      24220
Free To Play             14462
Early Access             13119
Sports                    5492
Racing                    4548
Massively Multiplayer     2876
Utilities                 1094
Design & Illustration      583
Animation & Modeling       480
Education                  466
Violent                    406
Video Production           340
Game Development           322
Gore                       255
Audio Production           227
Software Training          221
Photo Editing              181
Web Publishing             112
Nudity                      91
Sexual Content              86
Accounting                  31
Movie                        2
Documentary                  1
Episodic                     1
Short                        1
Tutorial                     1
360 Video                    1
Aventure                     1
Occasionnel                  1
Indépendant                  1
Stratégie                    1
Aventura                     1
Simuladores                  1
インディー                        1
早期アクセス                       1
Strategie                    1
Gratuit                      1
Name: count, dtype: int64

### The genres_clean column contains genres in different languages. We need to fix that. Later, we will do the same with the categories_clean column.

In [16]:
genre_replacements = {
    'Aventure': 'Adventure',
    'Occasionnel': 'Casual',
    'Indépendant': 'Indie',
    'Stratégie': 'Strategy',
    'Aventura': 'Adventure',
    'Simuladores': 'Simulation',
    'インディー': 'Indie',
    '早期アクセス': 'Early Access',
    'Strategie': 'Strategy',
    'Gratuit': 'Free To Play'
}

In [17]:
df2['genres_clean'] = df2['genres_clean'].apply(lambda genres: [genre_replacements.get(genre, genre) for genre in genres])

In [18]:
df2['genres_clean'].explode().value_counts()

genres_clean
Indie                    93692
Casual                   59021
Action                   52419
Adventure                51055
Simulation               28783
Strategy                 26689
RPG                      24220
Free To Play             14463
Early Access             13120
Sports                    5492
Racing                    4548
Massively Multiplayer     2876
Utilities                 1094
Design & Illustration      583
Animation & Modeling       480
Education                  466
Violent                    406
Video Production           340
Game Development           322
Gore                       255
Audio Production           227
Software Training          221
Photo Editing              181
Web Publishing             112
Nudity                      91
Sexual Content              86
Accounting                  31
Movie                        2
Documentary                  1
Episodic                     1
Short                        1
Tutorial                     1
360 Video                    1
Name: count, dtype: int64

### Clean the categories column

In [19]:
df2['categories'].explode().value_counts()

categories
["Single-player", "Family Sharing"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         21289
["Single-player", "Steam Achievements", "Family Sharing"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    9201
[]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           8963
[{"id": 2, "description": "Single-player"}, {"id": 62, "description": "Family Sharing"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     4690
["Single-player"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            4354
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
["Single-player", "Steam Achievements", "Custom Volume Controls", "Touch Only Option", "Steam Cloud", "Family Sharing"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
["Single-player", "Full controller support", "Camera Comfort", "Playable without Timed Input", "Family Sharing"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
[{"id": 2, "description": "Single-player"}, {"id": 1, "description": "Multi-player"}, {"id": 9, "description": "Co-op"}, {"id": 38, "description": "Online Co-op"}, {"id": 21, "description": "Downloadable Content"}, {"id": 62, "description": "Family Sharing"}]                                                                                                                                                                                                                                                                                                                             1
[{"id": 2, "description": "Single-player"}, {"id": 1, "description": "Multi-player"}, {"id": 9, "description": "Co-op"}, {"id": 38, "description": "Online Co-op"}, {"id": 27, "description": "Cross-Platform Multiplayer"}, {"id": 21, "description": "Downloadable Content"}, {"id": 22, "description": "Steam Achievements"}, {"id": 60, "description": "Gamepad Recommended"}, {"id": 59, "description": "Steam Input API Support"}, {"id": 18, "description": "Partial Controller Support"}, {"id": 23, "description": "Steam Cloud"}, {"id": 62, "description": "Family Sharing"}]        1
[{"id": 2, "description": "Single-player"}, {"id": 1, "description": "Multi-player"}, {"id": 21, "description": "Downloadable Content"}, {"id": 29, "description": "Steam Trading Cards"}, {"id": 62, "description": "Family Sharing"}]                                                                                                                                                                                                                                                                                                                                                         1
Name: count, Length: 21073, dtype: int64

In [20]:
df2['categories_clean'] = df2['categories'].apply(clean)
df2['categories_clean'].explode().value_counts()

categories_clean
Single-player              125294
Family Sharing             115252
Steam Achievements          65719
Steam Cloud                 37004
Full controller support     29537
                            ...
Mai mulți jucători              1
PvP online                      1
Cooperativ                      1
Cooperativ online               1
Achiziții în aplicație          1
Name: count, Length: 98, dtype: int64

In [21]:
# temporarily display more rows to see all the values
with pd.option_context('display.max_rows', 98):
    print(df2['categories_clean'].explode().value_counts())

categories_clean
Single-player                                  125294
Family Sharing                                 115252
Steam Achievements                              65719
Steam Cloud                                     37004
Full controller support                         29537
Multi-player                                    23521
Partial Controller Support                      15016
Playable without Timed Input                    14539
PvP                                             14511
Custom Volume Controls                          14000
Co-op                                           12960
Steam Trading Cards                             11595
Steam Leaderboards                              10595
Online PvP                                      10386
Remote Play Together                             8515
Shared/Split Screen                              8336
Online Co-op                                     8292
Save Anytime                                     7978
Stereo Sound                                     7864
Mouse Only Option                                6872
Stats                                            6051
VR Only                                          5980
Tracked Controller Support                       5729
Shared/Split Screen PvP                          5694
Camera Comfort                                   5245
Adjustable Difficulty                            4922
Keyboard Only Option                             4867
Shared/Split Screen Co-op                        4813
In-App Purchases                                 3490
Cross-Platform Multiplayer                       3416
DualShock Controller Support                     3225
Steam Workshop                                   3046
DualSense Controller Support                     2949
Includes level editor                            2883
Color Alternatives                               2763
Remote Play on TV                                2739
Surround Sound                                   1925
Touch Only Option                                1820
Captions available                               1667
Adjustable Text Size                             1604
MMO                                              1535
Subtitle Options                                 1405
LAN PvP                                          1273
#category_playable_at_your_own_pace              1251
VR Supported                                     1248
LAN Co-op                                        1228
Remote Play on Tablet                            1138
Remote Play on Phone                              983
Gamepad Recommended                               655
HDR available                                     496
Narrated Game Menus                               433
Commentary available                              304
VR Support                                        234
Steam Input API Support                           177
#category_contrast_controls                       156
Steam Timeline                                    142
Valve Anti-Cheat enabled                          113
Steam Turn Notifications                          107
Includes Source SDK                                63
Chat Text-to-speech                                51
Chat Speech-to-text                                38
SteamVR Collectibles                               38
#category_playable_without_vision                  22
Downloadable Content                               15
Solo                                                2
Succès Steam                                        2
Contrôle du volume différencié                      2
Difficulté ajustable                                2
Partage familial                                    2
Mods                                                2
Mods (require HL2)                                  2
Compat. contrôleurs complète                        1
Option clavier uniquement                           1
Option souris uniquement                            1
Option tactile uniquement                           1
Caméra et confort de vue                            1
Jouable sans saisie en temps imparti                1
Un jugador                                          1
Multijugador                                        1
Cooperativos                                        1
Cooperativos en línea                               1
Logros de Steam                                     1
Comodidad de la cámara                              1
Controles de volumen personalizados                 1
Se puede jugar sin eventos de acción rápida         1
Sonido estéreo                                      1
Préstamo familiar                                   1
シングルプレイヤー                                           1
マルチプレイヤー                                            1
協力プレイ                                               1
オンライン協力プレイ                                          1
ファミリーシェアリング                                         1
Un jucător                                          1
Mai mulți jucători                                  1
PvP online                                          1
Cooperativ                                          1
Cooperativ online                                   1
Achiziții în aplicație                              1
Name: count, dtype: int64

In [22]:
category_replacements = {
    # French
    'Solo': 'Single-player',
    'Succès Steam': 'Steam Achievements',
    'Contrôle du volume différencié': 'Custom Volume Controls',
    'Difficulté ajustable': 'Adjustable Difficulty',
    'Partage familial': 'Family Sharing',
    'Compat. contrôleurs complète': 'Full controller support',
    'Option clavier uniquement': 'Keyboard Only Option',
    'Option souris uniquement': 'Mouse Only Option',
    'Option tactile uniquement': 'Touch Only Option',
    'Caméra et confort de vue': 'Camera Comfort',
    'Jouable sans saisie en temps imparti': 'Playable without Timed Input',

    # Spanish
    'Un jugador': 'Single-player',
    'Multijugador': 'Multi-player',
    'Cooperativos': 'Co-op',
    'Cooperativos en línea': 'Online Co-op',
    'Logros de Steam': 'Steam Achievements',
    'Comodidad de la cámara': 'Camera Comfort',
    'Controles de volumen personalizados': 'Custom Volume Controls',
    'Se puede jugar sin eventos de acción rápida': 'Playable without Timed Input',
    'Sonido estéreo': 'Stereo Sound',
    'Préstamo familiar': 'Family Sharing',

    # Japanese
    'シングルプレイヤー': 'Single-player',
    'マルチプレイヤー': 'Multi-player',
    '協力プレイ': 'Co-op',
    'オンライン協力プレイ': 'Online Co-op',
    'ファミリーシェアリング': 'Family Sharing',

    # Romanian
    'Un jucător': 'Single-player',
    'Mai mulți jucători': 'Multi-player',
    'PvP online': 'Online PvP',
    'Cooperativ': 'Co-op',
    'Cooperativ online': 'Online Co-op',
    'Achiziții în aplicație': 'In-App Purchases'
}

In [23]:
df2['categories_clean'] = df2['categories_clean'].apply(lambda categories: [category_replacements.get(category, category) for category in categories])

In [24]:
with pd.option_context('display.max_rows', 100):
    print(df2['categories_clean'].explode().value_counts())

categories_clean
Single-player                          125299
Family Sharing                         115256
Steam Achievements                      65722
Steam Cloud                             37004
Full controller support                 29538
Multi-player                            23524
Partial Controller Support              15016
Playable without Timed Input            14541
PvP                                     14511
Custom Volume Controls                  14003
Co-op                                   12963
Steam Trading Cards                     11595
Steam Leaderboards                      10595
Online PvP                              10387
Remote Play Together                     8515
Shared/Split Screen                      8336
Online Co-op                             8295
Save Anytime                             7978
Stereo Sound                             7865
Mouse Only Option                        6873
Stats                                    6051
VR Only                                  5980
Tracked Controller Support               5729
Shared/Split Screen PvP                  5694
Camera Comfort                           5247
Adjustable Difficulty                    4924
Keyboard Only Option                     4868
Shared/Split Screen Co-op                4813
In-App Purchases                         3491
Cross-Platform Multiplayer               3416
DualShock Controller Support             3225
Steam Workshop                           3046
DualSense Controller Support             2949
Includes level editor                    2883
Color Alternatives                       2763
Remote Play on TV                        2739
Surround Sound                           1925
Touch Only Option                        1821
Captions available                       1667
Adjustable Text Size                     1604
MMO                                      1535
Subtitle Options                         1405
LAN PvP                                  1273
#category_playable_at_your_own_pace      1251
VR Supported                             1248
LAN Co-op                                1228
Remote Play on Tablet                    1138
Remote Play on Phone                      983
Gamepad Recommended                       655
HDR available                             496
Narrated Game Menus                       433
Commentary available                      304
VR Support                                234
Steam Input API Support                   177
#category_contrast_controls               156
Steam Timeline                            142
Valve Anti-Cheat enabled                  113
Steam Turn Notifications                  107
Includes Source SDK                        63
Chat Text-to-speech                        51
Chat Speech-to-text                        38
SteamVR Collectibles                       38
#category_playable_without_vision          22
Downloadable Content                       15
Mods                                        2
Mods (require HL2)                          2
Name: count, dtype: int64

### Clean the tags column

In [25]:
df2['tags'].explode().value_counts()

tags
[]                                                                                                                                                                                                                                                                                                                                                                                            57281
{"Indie": 21, "Casual": 21}                                                                                                                                                                                                                                                                                                                                                                      78
{"Adventure": 21, "Casual": 21, "Hidden Object": 6}                                                                                                                                                                                                                                                                                                                                              76
["Indie", "Casual"]                                                                                                                                                                                                                                                                                                                                                                              67
{"Action": 21, "Indie": 21}                                                                                                                                                                                                                                                                                                                                                                      67
                                                                                                                                                                                                                                                                                                                                                                                              ...
{"Racing": 54, "Simulation": 17}                                                                                                                                                                                                                                                                                                                                                                  1
{"Atmospheric": 1466, "Post-apocalyptic": 1356, "Open World": 1351, "FPS": 1258, "Survival": 1001, "Action": 740, "Survival Horror": 642, "Shooter": 632, "RPG": 628, "Horror": 601, "First-Person": 561, "Singleplayer": 554, "Classic": 493, "Based On A Novel": 407, "Moddable": 406, "Adventure": 399, "Immersive": 360, "Sci-fi": 350, "Inventory Management": 313, "Difficult": 290}        1
{"Strategy": 194, "Medieval": 126, "Historical": 90, "Grand Strategy": 83, "Singleplayer": 71, "Multiplayer": 68, "Moddable": 60, "RTS": 50, "Turn-Based Strategy": 45, "Turn-Based": 40, "War": 30, "Classic": 14, "Great Soundtrack": 12}                                                                                                                                                       1
{"Multiplayer": 604, "Strategy": 575, "FPS": 559, "Team-Based": 496, "Action": 447, "Sci-fi": 383, "RTS": 359, "Aliens": 312, "Indie": 296, "Competitive": 256, "Shooter": 201, "Co-op": 182, "Moddable": 174, "Tactical": 171, "First-Person": 141, "Space": 119, "Atmospheric": 109, "Futuristic": 109, "Online Co-Op": 106, "Adventure": 44}                                                   1
{"Action": 128, "Indie": 95, "Beat 'em up": 95, "2D": 77, "Side Scroller": 74, "Local Co-Op": 68, "Platformer": 54, "Gore": 39, "Singleplayer": 28, "Short": 20, "Adventure": 18, "Co-op": 16, "Controller": 16, "Hack and Slash": 12, "Old School": 11, "Multiplayer": 11, "Violent": 6, "Local Multiplayer": 5}                                                                                 1
Name: count, Length: 80290, dtype: int64

In [26]:
df2['tags_clean'] = df2['tags'].apply(clean)
df2['tags_clean'].explode().value_counts()

tags_clean
Singleplayer     40875
Indie            31218
Casual           26479
Action           24725
Adventure        24630
                 ...
Steam Machine        3
Masterpiece          3
Reboot               2
Tile-Matching        1
Football             1
Name: count, Length: 450, dtype: int64

In [27]:
with pd.option_context('display.max_rows', 450):
    print(df2['tags_clean'].explode().value_counts())

tags_clean
Singleplayer                         40875
Indie                                31218
Casual                               26479
Action                               24725
Adventure                            24630
2D                                   21987
3D                                   16811
Colorful                             12621
Atmospheric                          12569
Simulation                           12517
Puzzle                               12399
Strategy                             12178
Exploration                          11275
Pixel Graphics                       11250
RPG                                  11215
Cute                                 10828
Story Rich                           10241
First-Person                          9989
Fantasy                               9292
Arcade                                9142
Action-Adventure                      8665
Relaxing                              7923
Early Access                          7482
Funny                                 7463
Horror                                7448
Combat                                7177
Family Friendly                       7047
Retro                                 6956
Shooter                               6866
Stylized                              6494
Top-Down                              6487
Platformer                            6472
Multiplayer                           6468
Controller                            6257
Sci-fi                                6135
Anime                                 6030
2D Platformer                         5942
Third Person                          5883
Linear                                5813
Cartoony                              5421
Female Protagonist                    5412
Realistic                             5348
Mystery                               5271
Dark                                  5193
Survival                              4989
Choices Matter                        4906
Psychological Horror                  4903
Minimalist                            4859
PvE                                   4797
Physics                               4793
Multiple Endings                      4709
Visual Novel                          4513
Comedy                                4498
Rogue-like                            4160
Open World                            4106
PvP                                   4048
Point & Click                         3989
Rogue-lite                            3983
Hand-drawn                            3961
Logic                                 3862
FPS                                   3860
Old School                            3826
Difficult                             3799
Hidden Object                         3599
Magic                                 3580
Character Customization               3539
3D Platformer                         3525
Action RPG                            3414
Side Scroller                         3400
Co-op                                 3325
Sandbox                               3313
Management                            3270
Cartoon                               3226
Building                              3178
Puzzle-Platformer                     3155
Space                                 3106
Action Roguelike                      3093
Violent                               3091
Medieval                              3070
Tactical                              3069
Procedural Generation                 3052
Drama                                 3034
Immersive Sim                         3029
Futuristic                            3008
Interactive Fiction                   2932
Survival Horror                       2925
Free to Play                          2922
Bullet Hell                           2901
VR                                    2898
Choose Your Own Adventure             2812
Turn-Based Combat                     2769
Walking Simulator                     2767
Turn-Based Strategy                   2735
Turn-Based Tactics                    2719
Emotional                             2709
Score Attack                          2707
Nature                                2696
Sports                                2659
1990's                                2653
Shoot 'Em Up                          2644
Resource Management                   2627
Gore                                  2607
Crafting                              2551
Dark Fantasy                          2542
Surreal                               2465
Hack and Slash                        2375
Local Multiplayer                     2340
Sexual Content                        2329
Online Co-Op                          2318
Dungeon Crawler                       2288
Racing                                2266
Text-Based                            2162
Investigation                         2126
Precision Platformer                  2115
JRPG                                  2104
Top-Down Shooter                      2100
Education                             2086
Clicker                               2050
Zombies                               2044
Romance                               2031
Post-apocalyptic                      2020
Base-Building                         1992
1980s                                 1982
Life Sim                              1914
Thriller                              1897
War                                   1896
Cinematic                             1864
Historical                            1859
Narration                             1855
Nudity                                1853
Card Game                             1834
Abstract                              1827
2.5D                                  1794
Detective                             1773
Isometric                             1761
Stealth                               1760
Psychological                         1735
Local Co-Op                           1697
Demons                                1671
Time Management                       1670
Collectathon                          1651
Tabletop                              1606
Supernatural                          1582
Board Game                            1569
Military                              1561
Conversation                          1558
Dark Humor                            1557
Aliens                                1543
Third-Person Shooter                  1534
Dating Sim                            1525
Tower Defense                         1510
Economy                               1499
Strategy RPG                          1497
Perma Death                           1488
Robots                                1480
Tutorial                              1479
Idler                                 1465
Arena Shooter                         1464
Cyberpunk                             1462
Replay Value                          1448
Runner                                1432
Real Time Tactics                     1425
Lore-Rich                             1405
Nonlinear                             1385
Psychedelic                           1364
Driving                               1354
City Builder                          1276
RTS                                   1267
Wargame                               1260
LGBTQ+                                1229
Comic Book                            1222
Artificial Intelligence               1215
Modern                                1204
Great Soundtrack                      1188
Deckbuilding                          1185
Tactical RPG                          1181
Flight                                1158
Cats                                  1143
Grid-Based Movement                   1138
Short                                 1118
Inventory Management                  1106
Souls-like                            1101
Beat 'em up                           1094
Fast-Paced                            1083
Dystopian                             1058
Parkour                               1057
Loot                                  1051
Party-Based RPG                       1048
Memes                                 1026
Mature                                1022
RPGMaker                              1017
4 Player Local                         986
Metroidvania                           965
Card Battler                           962
2D Fighter                             959
Hentai                                 951
Mythology                              921
Level Editor                           921
Alternate History                      916
Turn-Based                             915
Experimental                           907
Creature Collector                     907
CRPG                                   902
Team-Based                             896
Automobile Sim                         889
Crime                                  889
Destruction                            864
Rhythm                                 858
Massively Multiplayer                  829
Twin Stick Shooter                     812
Philosophical                          809
Automation                             799
Match 3                                795
3D Fighter                             790
Music                                  767
Farming Sim                            759
Word Game                              757
Dark Comedy                            748
Mystery Dungeon                        748
Utilities                              733
Capitalism                             722
Cozy                                   708
Solitaire                              693
NSFW                                   688
Design & Illustration                  688
Soundtrack                             680
Fighting                               670
Noir                                   661
Auto Battler                           652
Science                                645
Space Sim                              640
Swordplay                              637
3D Vision                              637
Colony Sim                             625
Lovecraftian                           618
6DOF                                   611
Sokoban                                610
Grand Strategy                         607
Spectacle fighter                      596
Class-Based                            595
Cooking                                595
Hero Shooter                           589
America                                589
Vehicular Combat                       583
Parody                                 565
Agriculture                            565
Dragons                                564
Bullet Time                            562
Gun Customization                      551
Software                               550
Combat Racing                          549
Competitive                            546
Conspiracy                             539
Moddable                               533
Underground                            527
Wholesome                              525
e-sports                               524
Split Screen                           518
Time Manipulation                      518
Martial Arts                           516
Quick-Time Events                      506
Looter Shooter                         489
God Game                               481
Dog                                    474
Voxel                                  464
Battle Royale                          462
Gothic                                 459
Trading                                454
Character Action Game                  449
Satire                                 443
FMV                                    439
Beautiful                              433
Action RTS                             432
Mining                                 419
World War II                           417
Dynamic Narration                      415
Mechs                                  412
Roguelike Deckbuilder                  405
Political                              392
Game Development                       392
Open World Survival Craft              389
Mouse only                             388
Faith                                  388
Co-op Campaign                         386
Narrative                              385
Ninja                                  384
Underwater                             380
Hunting                                372
Time Travel                            372
Hex Grid                               371
Fishing                                369
Programming                            363
Pirates                                357
Animation & Modeling                   357
Vampire                                349
Typing                                 341
Transportation                         338
Party Game                             336
Escape Room                            335
Tanks                                  334
Political Sim                          327
Immersive                              327
Blood                                  321
Minigames                              317
Hacking                                313
Classic                                304
Snow                                   297
Boomer Shooter                         295
Steampunk                              294
Dinosaurs                              293
Assassin                               293
Otome                                  286
Asynchronous Multiplayer               278
Politics                               275
Western                                274
Party                                  273
Time Attack                            256
Trading Card Game                      254
Gambling                               254
Trivia                                 252
MMORPG                                 251
Archery                                249
4X                                     246
Superhero                              246
On-Rails Shooter                       238
Naval                                  223
Video Production                       222
Trains                                 219
Sailing                                218
Foreign                                218
Remake                                 211
Football (Soccer)                      209
Diplomacy                              204
Heist                                  200
Spelling                               198
Addictive                              194
Real-Time                              191
Cold War                               190
Music-Based Procedural Generation      186
Offroad                                185
Naval Combat                           181
Traditional Roguelike                  180
MOBA                                   179
Boxing                                 178
Sniper                                 171
Horses                                 170
Mars                                   168
Jet                                    165
Unforgiving                            164
Audio Production                       163
Farming                                156
Golf                                   155
Chess                                  154
Outbreak Sim                           153
Nostalgia                              153
Experience                             149
Transhumanism                          139
Roguevania                             139
Photo Editing                          136
Werewolves                             136
Real-Time with Pause                   133
Software Training                      133
Illuminati                             130
Motorbike                              128
Spaceships                             128
Bikes                                  121
Rome                                   119
Basketball                             117
Villain Protagonist                    116
Job Simulator                          115
Medical Sim                            115
Submarine                              114
World War I                            113
Asymmetric VR                          112
Sequel                                 111
Touch-Friendly                         108
Pinball                                107
Electronic Music                       106
Social Deduction                       103
Ambient                                 96
Mini Golf                               93
LEGO                                    91
Jump Scare                              89
Episodic                                87
360 Video                               85
Football (American)                     83
GameMaker                               79
Web Publishing                          79
Tennis                                  78
Pool                                    77
Instrumental Music                      77
Intentionally Awkward Controls          74
Cycling                                 73
Baseball                                73
Movie                                   70
Boss Rush                               68
Wrestling                               67
Dungeons & Dragons                      65
Skateboarding                           65
Motocross                               65
Cult Classic                            64
Skating                                 62
Gaming                                  62
Mahjong                                 59
Hockey                                  58
Silent Protagonist                      55
Bowling                                 52
8-bit Music                             47
Well-Written                            46
Skiing                                  45
Lemmings                                44
Vikings                                 44
BMX                                     44
Shop Keeper                             43
Dwarf                                   43
Rock Music                              41
Epic                                    40
Snowboarding                            38
Electronic                              36
Extraction Shooter                      35
Dice                                    34
Mod                                     33
Birds                                   32
ATV                                     32
Warhammer 40K                           30
Games Workshop                          29
Kickstarter                             28
Coding                                  26
Voice Control                           25
Crowdfunded                             23
Based On A Novel                        21
Fox                                     21
Musou                                   17
Volleyball                              17
Documentary                             17
Hardware                                17
Hobby Sim                               14
Rugby                                   13
Cricket                                 13
Benchmark                               13
Elf                                     10
Feature Film                             9
Snooker                                  7
TrackIR                                  6
VR Only                                  4
Steam Machine                            3
Masterpiece                              3
Reboot                                   2
Tile-Matching                            1
Football                                 1
Name: count, dtype: int64

In [28]:
# df2

### At this stage, I identified that the original dataset lacked some information needed for a more meaningful analysis. To enrich the dataset, I retrieved additional game-level data from the Gamalytic API. The full retrieval and pagination process is documented in Retrieving_Gamalytic_API.ipynb.

In [ ]:
df_new_sales = pd.read_csv(r"C:\Users\path\to\steam_sales_cleaned.csv")

matched_ids = df2['app_id'].isin(df_new_sales['steamId'])

matched_ids.value_counts()

app_id
True     128594
False     12147
Name: count, dtype: int64

### Check if the app_id and the steamId matches for two different games

In [30]:
df2[df2['name'].str.contains('Subnautica 2')]

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,average_playtime_2weeks,median_playtime_2weeks,achievements,dlc_count,windows,mac,linux,genres_clean,categories_clean,tags_clean
33347,1962700,Subnautica 2,2026-05-14,29.99,paid,"0 .. 20,000","[""Unknown Worlds Entertainment""]","[""Unknown Worlds Entertainment""]","[""Action"", ""Adventure"", ""Early Access""]","[""Single-player"", ""Multi-player"", ""Co-op"", ""On...",...,0,0,NaN,1,True,False,False,"[Action, Adventure, Early Access]","[Single-player, Multi-player, Co-op, Online Co...",[]

In [31]:
df2[df2['name'].str.contains('Counter-Strike 2')]

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,average_playtime_2weeks,median_playtime_2weeks,achievements,dlc_count,windows,mac,linux,genres_clean,categories_clean,tags_clean
126775,730,Counter-Strike 2,2012-08-21,0.0,free,"100,000,000 .. 200,000,000","[""Valve""]","[""Valve""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 1, ""description"": ""Multi-player""}, {""i...",...,0,0,1.0,1,True,False,True,"[Action, Free To Play]","[Multi-player, Cross-Platform Multiplayer, Ste...",[]

In [32]:
df_new_sales[df_new_sales['name'].str.contains('Subnautica 2')]

,steamId,name,copiesSold,earlyAccess,publisherClass,reviewScore
114,1962700,Subnautica 2,4745777,True,AA,91

In [33]:
df_new_sales[df_new_sales['name'].str.contains('Counter-Strike 2')]

,steamId,name,copiesSold,earlyAccess,publisherClass,reviewScore
0,730,Counter-Strike 2,357357808,False,AAA,86

### Merge df2 and df_new_sales dataframes

In [34]:
df2 = df2.merge(
    df_new_sales,
    left_on='app_id',
    right_on='steamId',
    how='left'
)

In [35]:
df2.shape

(140741, 35)

### After merging the two datasets using a left join, I created a separate DataFrame containing only the games that had matching records in both datasets. Games without a corresponding steamId from the Gamalytic dataset were excluded from df_matched.

In [36]:
df_matched = df2[df2['steamId'].notna()].copy() #df2['steamId'].notna() checks which rows have a non-missing steamId
df_matched.shape

(128594, 35)

In [37]:
# df_matched

### Finally, I deleted the repeated columns and the ones that had the old useless information

In [38]:
df_clean = (
    df_matched
    .drop(columns=[
        'genres',
        'categories',
        'tags',
        'steamId',
        'name_y'
    ])
    .rename(columns={
        'genres_clean': 'genres',
        'categories_clean': 'categories',
        'tags_clean': 'tags',
        'name_x': 'name'
    })
)

In [39]:
df_clean.columns

Index(['app_id', 'name', 'release_date', 'price', 'price_status',
       'estimated_owners', 'developers', 'publishers', 'positive', 'negative',
       'recommendations', 'peak_ccu', 'metacritic_score', 'user_score',
       'average_playtime_forever', 'median_playtime_forever',
       'average_playtime_2weeks', 'median_playtime_2weeks', 'achievements',
       'dlc_count', 'windows', 'mac', 'linux', 'genres', 'categories', 'tags',
       'copiesSold', 'earlyAccess', 'publisherClass', 'reviewScore'],
      dtype='str')

In [40]:
df_clean.shape

(128594, 30)

### Last glance at the dataframe:

In [41]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 128594 entries, 0 to 140725
Data columns (total 30 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   app_id                    128594 non-null  int64
 1   name                      128593 non-null  str
 2   release_date              128559 non-null  str
 3   price                     128434 non-null  float64
 4   price_status              128594 non-null  str
 5   estimated_owners          128594 non-null  str
 6   developers                128594 non-null  str
 7   publishers                128594 non-null  str
 8   positive                  128594 non-null  int64
 9   negative                  128594 non-null  int64
 10  recommendations           95728 non-null   float64
 11  peak_ccu                  128594 non-null  int64
 12  metacritic_score          88732 non-null   float64
 13  user_score                128594 non-null  int64
 14  average_playtime_forever  128594 non-null  int64
 15  median_playtime_forever   128594 non-null  int64
 16  average_playtime_2weeks   128594 non-null  int64
 17  median_playtime_2weeks    128594 non-null  int64
 18  achievements              111698 non-null  float64
 19  dlc_count                 128594 non-null  int64
 20  windows                   128594 non-null  object
 21  mac                       128594 non-null  object
 22  linux                     128594 non-null  object
 23  genres                    128594 non-null  object
 24  categories                128594 non-null  object
 25  tags                      128594 non-null  object
 26  copiesSold                128594 non-null  float64
 27  earlyAccess               128594 non-null  object
 28  publisherClass            128594 non-null  str
 29  reviewScore               128594 non-null  float64
dtypes: float64(6), int64(10), object(7), str(7)
memory usage: 41.1+ MB

### Change the data type of release_date from str to datetime and of copeisSold from float64 to int

In [45]:
df_clean['release_date'] = pd.to_datetime(df_clean['release_date'], errors='coerce')

In [46]:
df_clean['copiesSold'] = df_clean['copiesSold'].astype('int64')

In [ ]:
# df_clean.to_csv(r"C:\Users\path\to\steam_games_clean.csv", index=False)

In [ ]:
df_clean.to_parquet(r"C:\Users\path\to\steam_games_clean.parquet", index=False)